const professionalSectors = [
    {
      sector: "Healthcare",
      professions: [
        "Doctor",
        "Nurse",
        "Pharmacist",
        "Surgeon",
        "Physiotherapist",
        "Radiologist",
        "Dentist",
        "Paramedic",
        "Medical Laboratory Scientist",
        "Occupational Therapist",
      ],
    },
    {
      sector: "Engineering",
      professions: [
        "Civil Engineer",
        "Mechanical Engineer",
        "Electrical Engineer",
        "Software Engineer",
        "Structural Engineer",
        "Aerospace Engineer",
        "Chemical Engineer",
        "Biomedical Engineer",
        "Industrial Engineer",
        "Environmental Engineer",
      ],
    },
    {
      sector: "Finance",
      professions: [
        "Accountant",
        "Financial Analyst",
        "Investment Banker",
        "Auditor",
        "Actuary",
        "Risk Manager",
        "Tax Consultant",
        "Loan Officer",
        "Treasurer",
        "Budget Analyst",
      ],
    },
    {
      sector: "Education",
      professions: [
        "Teacher",
        "Lecturer",
        "School Counselor",
        "Curriculum Developer",
        "Special Education Teacher",
        "Principal",
        "Education Consultant",
        "Librarian",
        "Tutor",
        "Researcher",
      ],
    },
    {
      sector: "Information Technology",
      professions: [
        "Software Developer",
        "Data Scientist",
        "Cybersecurity Analyst",
        "IT Support Specialist",
        "Web Developer",
        "Network Administrator",
        "Database Administrator",
        "Cloud Engineer",
        "DevOps Engineer",
        "UI/UX Designer",
      ],
    },
    {
      sector: "Marketing",
      professions: [
        "Marketing Manager",
        "Digital Marketer",
        "SEO Specialist",
        "Social Media Manager",
        "Market Research Analyst",
        "Brand Strategist",
        "Content Creator",
        "Public Relations Specialist",
        "Copywriter",
        "Advertising Executive",
      ],
    },
    {
      sector: "Law",
      professions: [
        "Lawyer",
        "Judge",
        "Legal Advisor",
        "Corporate Attorney",
        "Paralegal",
        "Public Defender",
        "Prosecutor",
        "Immigration Attorney",
        "Notary Public",
        "Compliance Officer",
      ],
    },
    {
      sector: "Hospitality",
      professions: [
        "Hotel Manager",
        "Chef",
        "Bartender",
        "Event Planner",
        "Travel Agent",
        "Housekeeping Manager",
        "Front Desk Receptionist",
        "Tour Guide",
        "Concierge",
        "Food and Beverage Manager",
      ],
    },
    {
      sector: "Construction",
      professions: [
        "Architect",
        "Civil Engineer",
        "Construction Manager",
        "Site Supervisor",
        "Electrician",
        "Plumber",
        "Carpenter",
        "Mason",
        "Surveyor",
        "HVAC Technician",
      ],
    },
    {
      sector: "Retail",
      professions: [
        "Sales Associate",
        "Store Manager",
        "Cashier",
        "Inventory Specialist",
        "Merchandiser",
        "Customer Service Representative",
        "E-commerce Manager",
        "Warehouse Manager",
        "Retail Buyer",
        "Visual Merchandiser",
      ],
    },
  ];
  
  export default professionalSectors;
  